target-version = "py310"

[lint]
select = [
    "I", # isort
    "PL", # pylint
]

ignore = [
    "PLC0206",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR1730",
    "PLR2004",
    "PLW2901",
]
